version: '3.7'

networks:
  internal:
  external:

volumes:
  dynamodbdata:

services:
  session_cache:
    image: redis
    networks:
      - internal
      - external
  dynamodb:
    image: amazon/dynamodb-local
    working_dir: /home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    volumes:
      - dynamodbdata:/home/dynamodblocal
    networks:
      - internal
      - external
