name: Lint, Build, Test, and Publish (master)
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/lerna/lerna/issues/2542
      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: '0'

      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Use cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}

      - name: Lint
        run: yarn lint
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}

      - name: Build
        run: yarn build
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}

      - name: Test
        run: yarn test
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}

      - name: report code coverage
        run: npx codecov@3
        env:
          CI: true
          FONTAWESOME_TOKEN: not-actually-used-but-necessary-here
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: not-actually-used-but-necessary-here

      - name: publish package(s) with changes
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'osu-wams github action'
          git config --global user.email 'noreply@oregonstate.edu'
          yarn publish:patch --yes
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
