name: Lint, Build, Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/lerna/lerna/issues/2542
      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: '0'

      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: Lint
        run: yarn lint
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: Build
        run: yarn build
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: Test
        run: yarn test
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: report code coverage
        run: npx codecov@3
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: deploy package(s)
        if: github.ref == 'refs/heads/master'
        run: yarn publish:patch
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
