name: Pull Request Lint and Test
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: Lint
        run: yarn lint
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: Build
        run: yarn build
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: Test
        run: yarn test
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

      - name: report code coverage
        run: npx codecov@3
        env:
          CI: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
